services:
  my_subgraph_calcite:
    build:
      context: .
      dockerfile_inline: |-
        FROM meta_connector:latest
        COPY ./ /etc/connector
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/ndc-calcite
    env_file:
      - .env.local
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "8081"
        protocol: tcp

